### ISSUE TITLE
PinCtrl

### ISSUE THREAD

**Issue by waamber** [nss-evening-cohort-06/pinterest-flaming-marshmallows#14]
# Story
As a user, when I click on the "Pins" menu link, I should see all pins that I have added to all boards printed in rows of 4 cards per row. When I click an X on a pin, that pin should be deleted from firebase. When I click on the edit icon, I should be directed to an editable form with all information pre-loaded and a submit button. When I click the "tired" icon, the pin will also show on the "tried" page. 

# Acceptance Criteria 
**When** the user clicks on an x button on a pin
**Then**  that pin should be deleted from firebase
**And** the pins page should be updated to not include that pin

**When** the user clicks on the edit button
**And** the user edits the info and clicks submit
**Then** the pin info is updated in firebase.

**When** the user clicks on the tried button
**Then** the pin will also be populated on the "tried" page
**And** the key "tried" is updated to "true" in firebase

**Comment by waamber** [comment]
Add X button to pins card in pins.html

```ng-click="deletePin()"```

That should take in a pinId that calls PinterestService.deletePin(). This function will delete the pin from firebase.

**Comment by waamber** [comment]
Edit pin

```
$scope.editPin = (PinId) => {
    $location.path(`/boards/pins/edit/${$routeParams.id}`);
  };
```

**Comment by waamber** [comment]
```
$scope.moveToTried = (boardId) => {
    $location.path(`/boards/tried/${$routeParams.id}`);
  };
```

**Comment by kstoops815** [comment]
![pins view](https://user-images.githubusercontent.com/30006983/33353531-ee2ed220-d473-11e7-9a7e-72004b70aeb8.jpg)
