### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by DreRandaci** [nss-evening-cohort-06/pinterest-flaming-marshmallows#5]
# Story
In order for the user to see their boards on page load, these things need to be complete

# Acceptance Criteria
**When** the user logs in
**Then** they should see the boards associated with their UID

**When** the boards print
**Then** they should be aligned in a container
**And** the boards should be cards

**If** user has no boards associated with their profile
**Then** the user should be prompted to create a new board 

**When** the user creates a board
**Then** the user is taken to the createBoard.html

**When** the user clicks a board
**Then** the user should be taken to the editBoard.html partial

**Comment by DreRandaci** [comment]
home.html:
-if no boards, “create a new board” prompt should appear
-else, print boards associated with that user
-boards should be in a container
-boards should be cards
-createBoardObject(newBoard) function fired on ng-click of create new board

**Comment by kstoops815** [comment]
![home view](https://user-images.githubusercontent.com/30006983/33352940-e5f85958-d470-11e7-8b0b-47b6dea237ab.jpg)

**Comment by kstoops815** [comment]
move the "add board" to the beginning instead of the end.
