### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by DreRandaci** [nss-evening-cohort-06/pinterest-flaming-marshmallows#7]
# Story
These things need to be complete in order for users to navigate the site

# Acceptance Criteria
**When** the user is authenticated
**Then** there should be a navbar that appears

**And** the navbar should have a boards button
**And** the navbar should have a pins button
**And** the navbar should have a tried button 
**And** the navbar should have a logout button
(links should be right-justified)
**And** the navbar should have a logo (on the left)

**Comment by kstoops815** [comment]
![navbar](https://user-images.githubusercontent.com/30006983/33352612-5e330104-d46f-11e7-95a9-2c1057005214.jpg)

**Comment by kstoops815** [comment]
![navbar](https://user-images.githubusercontent.com/30006983/33352725-e285a98e-d46f-11e7-9edb-f23fdd436b15.jpg)
